{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysql.pvcName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.mysql.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.mysql.storage.accessMode }}
  storageClassName: {{ .Values.mysql.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.mysql.storage.size }}
{{- end }}
